nicQuotes = [
    "I Want To Take His Face... Off. Eyes, Nose, Skin, Teeth. It's Coming Off.",
    "Got My First Chemistry Set When I Was Seven, Blew My Eyebrows Off, We Never Saw The Cat Again, Been Into It Ever Since.",
    "Did I ever tell ya that this here jacket represents a symbol of my individuality, and my belief in personal freedom?",
    "Put... the bunny... back... in the box.",
    "I'll Be Taking These Huggies, And Whatever Cash You Got.",
    "Sorry Boss, But There's Only Two Men I Trust. One Of Them's Me. The Other's Not You."
    "Some Things Are True Whether You Believe In Them Or Not.",
    "People Don't Throw Things At Me Anymore. Maybe Because I Carry A Bow Around.",
    "I did a bare ass 360 triple back flip in front of twenty two thousand people. It's kind of funny, it's on Youtube, check it out. But when my dad got sick, I did something way crazier than that.",
    "It's so easy, even a child can use it; and they do.",
    "OH, NO! NOT THE BEES! NOT THE BEES! AAAAAHHHHH! OH, THEY'RE IN MY EYES! MY EYES! AAAAHHHHH! AAAAAGGHHH!",
    "I'M A VAMPIRE! I'M A VAMPIRE! I'M A VAMPIRE! I'M A VAMPIRE! I'M A VAMPIRE! ",
    "I'm gonna steal the Declaration of Independance",
    "I'll be damned if I didn't get really...turned on",
    "One time a naked home intruder ate a fudgsicle at the foot of my bed",
    "I was the victim of a massive comic book heist",
    "I bought a pyramid tomb for myself when I die",
    "I slept in Dracula's Castle",
    "I accidentally bought a stolen dinosaur skull",
    "I bought the most haunted mansion in the world so I could write a horror novel",
    "Me and my cat did shrooms once",
]
