import random
from giphyapi import get_nicgif

nicQuotes = [
    "I Want To Take His Face... Off. Eyes, Nose, Skin, Teeth. It's Coming Off.",
    "Got My First Chemistry Set When I Was Seven, Blew My Eyebrows Off, We Never Saw The Cat Again, Been Into It Ever Since.",
    "Did I ever tell ya that this here jacket represents a symbol of my individuality, and my belief in personal freedom?",
    "Put... the bunny... back... in the box.",
    "I'll Be Taking These Huggies, And Whatever Cash You Got.",
    "Sorry Boss, But There's Only Two Men I Trust. One Of Them's Me. The Other's Not You."
    "Some Things Are True Whether You Believe In Them Or Not.",
    "People Don't Throw Things At Me Anymore. Maybe Because I Carry A Bow Around.",
    "I did a bare ass 360 triple back flip in front of twenty two thousand people. It's kind of funny, it's on Youtube, check it out. But when my dad got sick, I did something way crazier than that.",
    "It's so easy, even a child can use it; and they do.",
    "OH, NO! NOT THE BEES! NOT THE BEES! AAAAAHHHHH! OH, THEY'RE IN MY EYES! MY EYES! AAAAHHHHH! AAAAAGGHHH!",
    "I'M A VAMPIRE! I'M A VAMPIRE! I'M A VAMPIRE! I'M A VAMPIRE! I'M A VAMPIRE! ",
    "I'm gonna steal the Declaration of Independance",
    "I'll be damned if I didn't get really...turned on",
    "One time a naked home intruder ate a fudgsicle at the foot of my bed",
    "I was the victim of a massive comic book heist",
    "I bought a pyramid tomb for myself when I die",
    "I slept in Dracula's Castle",
    "I accidentally bought a stolen dinosaur skull",
    "I bought the most haunted mansion in the world so I could write a horror novel",
    "Me and my cat did shrooms once",
    "I am not a demon. I am a lizard, a shark, a heat-seeking panther. I want to be Bob Denver on acid playing the accordion.",
    "I'm going to steal the Declaration of Independence.",
    "Some things are true whether you believe in them or not.",
    "Every great story seems to begin with a snake.",
    "Those who have the ability to take action have the responsibility to take action.",
    "I like both Blu-ray and DVD, but Blu-ray gives you more options.",
    "To be a good actor you have to be something like a criminal, to be willing to break the rules to strive for something new.",
    "I don't drink blood, and last time I looked in the mirror, I had a reflection.",
    "There's a fine line between the Method actor and the schizophrenic.",
    "I don't know if my wife left me because of my drinking or I started drinking 'cause my wife left me.",
    "Passion is very important to me. If you stop enjoying things, you've got to look at it, because it can lead to all kinds of depressing scenarios.",
    "Sometimes people think I'm wearing a wig when I'm not wearing a wig, and then sometimes they think I'm not wearing a wig when I am wearing a wig.",
    "I'm legally unable to ride motorcycles. It's a contract that I have with my life insurance, so whenever I get a chance to do a movie and ride a bike I go for it.",
    "Shock is still fun. I won't ever shut the door on it.",
    "You can't make your choices based on what critics think. You have to make your choices based on what's honest for you.",
    "The end of the world is on people's minds. We have the power to destroy or save ourselves, but the question is what do you do with that responsibility.",
    "We've become so glorified in the movie-star system that it's become this artificial royalty. The truth is that we're circus clowns.",
    "I remember once imagining what my life would be like, what I'd be like. I pictured having all these qualities, strong positive qualities that people could pick up on from across the room. But as time passed, few became qualities that I actually had. And all the possibilities I faced, and the sorts of people I could be, all of them got reduced every year to fewer and fewer until finally they got reduced to one - to who I am. And that's who I am.",
    "Nobody ever thinks clearly at the airport.",
    "Don't lose the best thing in your life just because you are not sure.",
    "I do like to move and get physical in my movies.",
    "I think it's no secret that I've tried to take chances in my career and also in my life, and I believe to not live in fear.",
    "To begin... To begin... How to start? I'm hungry. I should get coffee. Coffee would help me think. Maybe I should write something first, then reward myself with coffee. Coffee and a muffin. Okay, so I need to establish the themes. Maybe a banana-nut. That's a good muffin.",
    "I cry a lot. My emotions are very close to my surface. I don't want to hold anything in so it festers and turns into pus - a pustule of emotion that explodes into a festering cesspool of depression.",
    "If you're really special, meaning you're doing something unique and original, it could scare people.",
    "I think what makes people fascinating is conflict, it's drama, it's the human condition. Nobody wants to watch perfection.",
    "I guess it would fall into the stalker category more or less. I was being stalked by a mime - silent but maybe deadly. Somehow, this mime would appear on the set of 'Bringing Out the Dead' and start doing strange things. I have no idea how it got past security. Finally, the producers took some action and I haven't seen the mime since. But it was definitely unsettling.",
    "My mother was a dancer, so I like to use the body as part of the instrument of acting.",
    "I want to always find new ways of reinventing myself.",
    "I always add a year to myself, so I'm prepared for my next birthday. So when I was 39, I was already 40.",
    "One of the pluses of getting older is you set some limits.",
    "I don't like it when people on the street say \"smile\" or \"cheer up.\" It's a real cheap line. I'm feeling good. I'm feeling real grateful for everything. It's a solid time in my life. When people say I look sad, they're wrong.",
    "I like being at that place where you can either fall or stand. That's where I think you really have a shot at doing something truthful.",
    "I always say, if you think it\u2019s over the top then tell me where the top is first. I don\u2019t think anyone can. But if you can tell me where the top is then I\u2019ll tell you whether or not I\u2019m over it.",
    "I'm sticking my tongue out in scenes to try to make that work in 3D. I'm thinking I'll try to get my tongue all the way out to the second row of the audience.",
    "The only way the devil really exists in my opinion... is in interactions with people who don't walk the walk and talk the talk; people who act one way, or talk one way and then do another. Those are the deals with the devil. I don't see the devil as somebody who is a horned, goateed guy with a fork in his hand that's there to continuously stab me and send my soul to hell. I don't see it that way at all.",
    "I love all animals. I have a fascination with fish, birds, whales - sentient life - insects, reptiles.",
    "I believe that everybody has the right to believe what they want to believe and to knock somebody's faith and religion is foolish, whatever it may be - Christianity, Judaism, Islam, Buddhism.",
    "I'm a seeker. I'm very much a believer in science. But I do think there are times when science and mysticism intersect.",
    "Snakes are sometimes perceived as evil, but they are also perceived as medicine. If you look at an ambulance, there's the two snakes on the side of the ambulance. The caduceus, or the staff of Hermes, there's the two snakes going up it, which means that the venom can also be healing.",
    "I know what it's like to meet someone you admire and have them be a complete jerk.",
    "I have eclectic tastes in the movies I want to do.",
    "Tattoos to me are the outward symbol of the inward change within my soul.",
    "You can choose your family sometimes. You can choose people, it could be a teacher, it could be a professor, it could be someone you work with that actually genuinely cares about you and wants you to succeed.",
    "I'm always going to judge somebody on their work ethic, and whether or not they made me feel something, or whether or not I felt they did a good job. To me, it's important to try to block anything personal out and look at the performance, in any field.",
    "I think on some level, all of us have a little bit of belief in the possibility of different energies and forces and things like that. Otherwise, we wouldn't be afraid of them. Or there wouldn't be so many movies about them.",
    "You aren't a true internationalist until you've supplied weapons to kill your own countrymen.",
    "If you have people that totally support you and have your back, I feel like you have all the confidence in the world, and you believe that you can do things that most people can't achieve. I feel that's really important.",
    "I hit the ground running, without a lot of training, so I had to do whatever I could do to survive as a professional, and if that meant being that character 24/7 and acting out, I was going to do that. I lived those characters, I brought them home with me.",
    "I believe that there's a way to question authority with manners, with dignity. There's no reason to be rude about it.",
    "As I got older, with my work, I became aware of the responsibility of film, and I feel one of the best ways I can apply myself as an actor, is to go beyond movie stardom and celebrity.",
    "Well, Amber [Heard] is still raising her eyebrow at me because I said that I've been 180 miles per hour on the 405 freeway on a motorcycle and she doesn't believe me but it's a true story. I did it coming home from work at 3 in the morning on another movie I made about cars called Gone in 60 Seconds. I bought a Yamaha-1 and I was doing 180 miles per hour home on the 405 and that's really, really crazy but I did it.",
    "I needed to change my name just to liberate myself and find out I could do it without walking into a Hollywood casting office with the name Coppola.",
    "It's important to keep the eccentric spirit alive, because when that goes, the work will go.",
    "My definition of a father is someone who empowers their children.",
    "I think I jump around more when I'm alone.",
    "I always see America as really belonging to the Native Americans. Even though I'm American, I still feel like a visitor in my own country.",
    "I was always shocked when I went to the doctor's office and they did my X-ray and didn't find that I had eight more ribs than I should have or that my blood was the color green.",
    "I think anything that opens my mind and triggers my imagination I'm reading. I like to read science fiction and imagine the character. Anything that keeps my imagination flowing.",
    "My best takes are my first two takes.",
    "I'm at the point now where I know I'm doing something right when a movie gets mixed reviews, because then I'm not in the box. I don't want to make it too easy for people and I don't want to make it too easy for myself. I want to try something unusual.",
    "Yeah, my real name is Coppola. I changed it because they'd think I was some nepotism-oriented kid.",
    "I think I've become more relaxed throughout my career. I don't feel the need to jump up and down and make a big noise to get people to pay attention to me. I don't need to do punk rock gestures or eat a cockroach or do something weird to say I exist.",
    "Science fiction is a way that I can go into the abstract, go into the imagination, and audiences are still willing to go along for the ride.",
    "With my name in cement, I feel actualised. - On cementing his hand prints on Sunset Boulevard",
    "There are over 550 million firearms in worldwide circulation. That's one firearm for every twelve people on the planet. The only question is, how do we arm the other 11?",
    "I don't think movies are the reason why this violence exists, I think it's going to happen whether movies are there or not.",
    "It's always exciting when you can go into a mode where you can be both spontaneous and choreographed. Sort of in control and out of control at the same time.",
    "My father once said, 'If you're in the desert and you're dying of thirst, are you going to drink a glass of blood or are you going to drink a glass of water?' I think what he was trying to say, interesting coming from my blood father, is sometimes there are people in your family that can be toxic.",
    "Actors have an opportunity to use storytelling as a way to solve pain.",
    "I love it all. I don't want to go through my career with one hand tied behind my back. I love making kids happy. I love the midnight audience. I like intense dramas. And I like high-adrenaline action films.",
    "One of the great bonuses of being a film actor is that I get to go to different places, meet inspiring people and learn different things. So all those details add up.",
    "I care about the connection with the audience. Film is such a powerful medium. Movies can change the way people think.",
    "Often you hear stories about never working with children. I disagree because children still have that residual magical thinking. They haven't had their imagination knocked out of them by turning into adults and life experiences.",
    "It may come as a surprise to people, but I'm actually quite boring and normal. What do I do? I read books. I drive my kid to school. I have lunch with my wife. I pick my kid up from school. I go home.",
    "I do enjoy animated movies. I really love anime and movies like 'Spirited Away' and 'Howl's Moving Castle.'",
    "I'm not really interested in playing famous people. I prefer to create characters. And I hope I have an exciting enough life that somebody might make a movie about that one day. I don't want to make movies about other people. I was once approached about playing Salvador Dali, which I thought would've been fun until I found out that he was proud of kicking a blind man across the street. So, I decided, I didn't want to play that guy. So, I think I'll just keep it the way it is.",
    "One of the first signs of being depressed is that you lose interest in things. That's why I think it is important to stay passionate.",
    "Nobody wants to watch perfection.",
    "I haven't made anything I don't believe in. I've always started a movie with a song in my heart, and even when I'm a little unclear about it, something magical happens and it comes into focus in a way that I'm feeling good about.",
    "I'm not a trained actor. I'm someone who is autodidactic and learned on my own.",
    "I think the paparazzi might have chased me out of Los Angeles.",
    "Everything we do impacts someone else's life.",
    "Picasso said art is a lie that tells the truth. What if you just want to tell the truth and not lie about it?",
    "I try not to be proud. I try to actively attack pride.",
    "I've always maintained that I see myself as a student. There's always something to learn and be challenged by and hopefully grow from.",
    "Peter Fonda is the reason I became a motorcyclist. I saw Easy Rider and I bought a motorcycle the next day, and I rode it all the way from LA to San Francisco.",
    "I think that movies can help guide us through those experiences [the problems that are happening in our daily lives, the stresses between countries, the economy and global warming]. I think all art tries to grapple with, redefine, come to terms with, express what's happening now when it's working. You can be entertained, but you can also be stimulated to think about things.",
    "I like to work with young people, because young people haven\u2019t had their dreams kicked out of them yet. Full of confidence, and imagination, and vision, and when they score that all gets empowered.",
    "I've been lucky to work with some of the most creative people and it's true that I enjoy filmmaking and I'm an enthusiast.",
    "My direction as a person working in film has been to never get comfortable with anything I was doing. At the time that I decided to do action films, people were telling me, \"Well, you can't do it. You're not that type. It's not going to work.\" And so obviously that made me think, \"Well, that's not comfortable. Maybe I should try it. What can I do with it?\" So I did that, and I'm glad I did it. I'll probably do it again, and I did other kinds of things that seemed like challenges for me, because I like being on the high wire.",
    "I see myself as a student. I would never call myself a master or a maestro. If you take the path of the student, that means you have to try a little bit of everything in hopes that you're going to learn something or strike some kind of new note, expression in the process. I'm not going for grades; I'm going for an education. I'm going to continue experimenting and trying new things to try to evolve and learn.",
    "We do see Gong Li, Zhang Ziyi and Chow Yun Fat, but it's very rare to see the Chinese male actor in Hollywood movies, which is something I take great umbrage with. You know, my son is Asian. He may want to direct one day; he may want to be an actor like his father - and I want that to be open to him.",
    "Someone like Vincent Price or somebody like Christopher Lee, they never won an award, and it doesn't matter. They're cool.",
    "When I won the Oscar, I made a point of actively going against that and doing adventure films like 'Con Air' and 'Gone in 60 Seconds,' not what would be expected.",
    "When I was eight, I would look at the cover of the 'Ghost Rider' comic book in my little home in Long Beach, California, and I couldn't get my head around how something that scary could also be good. To me it was my first philosophical awakening - 'How is this possible, this duality?'",
    "There is a misperception, if you will, in critical response or even in Hollywood, that I can only do exaggerated characters. Or what they would call over-the-top performances. Well, this is completely false.",
    "I will promise you that if I can give you two good scenes -- which is what I always try to do in every movie -- then I feel like I'm doing my job.",
    "I would like to find a way to embrace what Led Zeppelin did, in filmmaking.",
    "How do you rebel in a family of rebels?",
    "I didn't play the Ghost Rider in the first movie. That was a stuntman. In this film, the Ghost Rider feels much more alive because I did put some thought into how he should walk and into how he should move. I was so into the character, in fact, that I would paint my face with white and black makeup to look like a skull. And I put on blacked-out contact lenses, so I almost looked like an Afro-New Orleanian voodoo icon by the name of Baron Samedi. Oh man, I would walk around the set without saying a word to anybody, and I could see the fear in my co-stars' and co-directors' eyes.",
    "I have a love-hate relationship with New Orleans, which is the strongest sort of relationship. I've had some extraordinary, beautiful, poetic experiences in this city and I've had some terrible experiences in this city. I'm drawn to New Orleans, in many ways feel I grew up in New Orleans, even though I'm from the West.",
    "I wanted to make an image for myself as an outlaw type. A kind of rock 'n' roll sensibility.",
    "With the advent of this kind of TMZ culture, it sadly seems to have infiltrated the vanguard of film commentary. I see these reviews sometimes where I think, well, you have a right to say whatever you want about my work, and I will listen whether it's good or bad and see if there's something that I might work with, but personal issues don't have a place in film commentary.",
    "Most of my favourite moments in film have been when I've had an opportunity to say something from scratch, something original, whether I jotted down a few lines or it came out in improvisation.",
    "First of all the criteria that I have that goes into any career decision is whether or not I have the life experience, emotional resources to play the part truthfully or the imagination. Second, would be the director.",
    "If I could have been a marine biologist I would have, but I didn't have that kind of intelligence. Numbers were never my strong point.",
    "Well, good science fiction is intelligent. It asks big questions that are on people's minds. It's not impossible. It has some sort of root in the abstract. So automatically you're getting closer to potentially divine sources of interest because it is abstract. It's one of the only ways that a film actor can express himself in the abstract and have audiences still go along for the ride. They don't contend it. They accept it, that they're going to go places that are a bit more of the imagination, a bit more out there, and that's more and more where I like to dance.",
    "You get dinged for wanting to do a comedy, then wanting to do a big-budget action film, and then wanting to do an indie. But you can't let other people trying to label you get in the way of trying to do something artistically.",
    "I generally enjoy the rehearsal process because that's where you can share your ideas, get your thoughts and feelings out and see whether or not they're going to land, whether or not people are going to agree with them, particularly the director. So you can sort out in that process any elements that need to be sorted out before you're on the set, and of course that saves time and it also makes everyone more comfortable working together.",
    "Without mentioning any names, I looked at pretty much every story that may come to your mind about a politician on the rise who was stopped short or dragged down by personal flaws and then became just a media storm. I see this as a thing that continues to happen in America and I wanted to say something about that.",
    "Remakes are always a challenge and they always are sitting ducks.",
    "I use technology for communication, but I don't have a Blackberry or an iPhone. I use an outdated cell phone, but I'm fine with it.",
    "I'm not really gadget oriented. I'm not into technology or computers. I'm not good at interfacing with that sort of gear.",
    "I'm not afraid to play ugly - look at 'Adaptation.' I looked like a turd that a cat had coughed up.",
    "I'm not contractually obligated to sequels on anything.",
    "I try to make two movies a year. To me, that's not too much. On top of that, I like to work.",
    "I want people to discover my movies, and however they choose to receive it is their business.",
    "Having been a father for 19 years I realise fatherhood has changed me.",
    "Just because you're a man doesn't mean that you can't raise your kid. I think that families should stay together, but if you are a single father, don't give up no matter what they say.",
    "I came out of independent film, that's my roots.",
    "My father was always getting excited about something. It's genetically inside me somewhere.",
    "As a teenager I was more of an anarchist, but now I want people to thrive and be harmonious.",
    "I've always had a soft spot for comic books. I learned to read from them. The words in them were so interesting.",
    "I like fantasy. I like horror, science fiction because I can get avant-garde with those performances in those movies.",
    "For me, acting was a way of taking destructive energy and doing something productive with it, and in that way it was quite a life saver.",
    "I have dogs, and it's no secret that I find reptiles interesting, but the thing about reptiles is that they really just wanna be left alone, and I understand them. It's, 'Don't pick me up, stop holding me, don't look at me, just leave me alone.' I have to admit, sometimes I feel like that.",
    "Acting is like any other art form, in that you have the option to go very big or go very small.",
    "Celebrity is a word I take great umbrage with. I'm actively anti-celebrity.",
    "I bought a Yamaha-1 and I was doing 180 miles per hour home on the 405 and that's really, really crazy but I did it.",
    "I definitely went through my magic phase. I think all little boys do at some point or another - they get fascinated by magic tricks.",
    "I try to do as many stunts as they'll let me do. I think it's important for an audience to feel that the actor's really doing it.",
    "Feel like real time unfolding. It's going to smack of reality and feel as real as it can ... The buildings themselves aren't (shown) ... The movie's about what happened amongst this handful of men when the buildings came down.",
    "I don't want to sit around by the pool luxuriating with a margarita. That's just not what I want to do.",
    "I happen to still like really dark, dramatic, fractured characters. They're the reason I got into movies.",
    "Film has lost something in the translation to high tech. It's become so super-real. It's with digital this and stereo that, and everything's like a CD.",
    "I do tend to apply myself to projects that make me uncomfortable because usually when that happens I try to find a way of existing in the project that is more creative.",
    "At a young age, I was interested in comic books, which was really how I learnt to read. The name Cage came from a comic book character called Power Man.",
    "One of my goals is to have a base near mainland China. I think Hong Kong would be a good match for me. I like being in Hong Kong.",
    "Actors, their greatest tool, their greatest resource is imagination. You can take things, power objects, you can recruit your dreams, you can access your memories and get there. So the idea is not to act but to just be.",
    "I think that 'Ghost Rider: Spirit of Vengeance' was mentally taxing, if only because I had to go to a Christmas party shortly after I had wrapped photography in Romania at two in the morning as the Ghost Rider. The invitation had a Christmas ornament on it with Ghost Rider's face on it as a tree.",
    "I would definitely return to Austria. They were all good experiences for me, but definitely Austria because there were some ancient Celtic, sacred sites that were in the forest that were quite beautiful.",
    "People are losing jobs, people need to be entertained, and I want to make movies that parents and children can look forward to seeing, that can become a kind of family ritual.",
    "Acting is always at the core of my life, but I'm also excited about producing. I'm excited about directing, and I have a life in the filmmaking world, and so I want to explore all aspects of it, not just the acting, but acting is the root.",
    "As a child, these colourful superheroes that could fly, or were horrifying like Ghost Rider and the Hulk, with this tremendous rage or these supernatural powers, provided an escape for me from my mundane existence, from my lack of friends or my inability to communicate well with people. They liberated me.",
    "I never studied dance, but if you look at 'Wild At Heart,' my mother saw that movie and said, 'You are a dancer. Look at how you're moving: all that strange energy is like modern dance.'",
    "Film acting is one of the only industries where you're criticized for working hard. In any other industry, it's considered a quality and something to behold.",
    "One day, one of my dreams is to someday get to do Nemo in '20,000 Leagues Under the Sea.'",
    "How do you say one actor is better than another actor? You can definitely say that in the Olympics if it's the same race and someone wins the race. The only way to really do it and have it be sincere would be if you get all the actors together, and they're all playing the same part, and then you rate which one made you feel the most.",
    "How do you rebel in a family of rebels? That's the age-old question. I guess I could have by not going into the arts, but the thing is, I couldn't do anything else.",
    "It's amazing marrying someone who wants nothing to do with Hollywood.",
    "Hopefully as a result of 'The Frozen Ground,' more and more people will be aware of the horrible things that happen to ladies all over the world and give them respect. This movie is a love letter to those victims.",
    "I'm not an anarchist any more. I still love the Sex Pistols, but I don't want to be a punk rocker all the time, but I do want to carry on exploring new forms of acting.",
    "I know there's been a lot that's been said about animated voice work, as though it's 'you can do this in your jeans and there's no camera and no pressure there. It's no big deal. It's easy.' The truth is, it's really a great test: how deep is your ability is to access your imagination?",
    "I like movies where you feel like you're going into another world, and no matter how many times you watch it, you're gonna see something new in that world. That level of detail really inspires me.",
    "I want to make all kinds of movies. I do want to make big movies that are a lot of fun to go to, but I also want to make movies that are going to stimulate some thought and maybe raise some awareness.",
    "And what I like about it is it makes me happy and I think it makes a lot of people happy to go to the movies and to not think about the problems of the day or the problems of tomorrow or the yesterday and just go on for the ride and have the fun of losing oneself in a fantasy.",
    "I'm an enormous admirer of Christopher Lee. He's somebody, along with Vincent Price, who I celebrate, and I wanted my movies to show that celebration and that honoring of these great film stars that were unafraid to go into horror and Grand Guignol and the macabre.",
    "I loved 'Fantasia' as a kid because it filled me with wonder, enchantment and awe. It was my first real introduction into classical music. It was totally inspiring to me.",
    "The movies I cannot go without and that I watch annually are 'A Clockwork Orange,' 'Scarface' and 'Fantasia.'",
    "The fact that 'Astro Boy' appealed to me as a boy in America was proof that the story and character transcend cultural stereotypes.",
    "I always say to myself that if I can make a movie that makes a kid smile or gives them some hope or something to get excited about, then I'm applying myself in the best way that I can. I don't think that just goes for kids. I think that it goes for adults, as well, and for families.",
    "I've always had an interest in Louisiana, especially New Orleans.",
    "I've always had a soft spot for comic books.",
    "I've acted professionally since I was 16.",
    "I'm very impressed with 'Drive.'",
    "I'm the first to admit that I like going to, or my memories at least of going to Clint Eastwood movies or Charles Bronson or James Bond.",
    "In this day and age, where you have a lot of comic book movies made every day, and most of them are really good boys, it's important to have a couple bad boys out there, too.",
    "If I do do a sequel, I'm going to have to know for sure that the script is better than the original. So I'm going to be very careful about that because I'm not eager to repeat myself.",
    "I've really had good luck working with younger actors. Every younger actor that I have worked with has always been really on top of their game and fascinating to watch.",
    "Zoology has always been interesting to me. Nature is fascinating.",
    "I've gotten pretty good at leaving characters on the set. I go home and try to relax and regroup and be ready for the next day.",
    "Personally, my interests are ancient history and ancient civilizations. In my own life, I'd like to go to places like Easter Island.",
    "I'm one of those people that feels that Americans that shouldn't do Shakespeare... The rhythms of the English language and the mannerisms of the English speech seems to work effortlessly with William Shakespeare, but when Americans do it, something seems stuck.",
    "When I act, I hear it like music. In my head, I hear the dialogue like music.",
    "Hollywood didn't know if I was an actor or a nut or if I was this crazy character I was playing. I had developed an image of being a little bit unusual, different and wild.",
    'Helen Mirren is someone that I have really admired ever since I saw her in Excalibur. That was the first thing I said to her. "I loved you as Morgan Le Fay."',
    "God bless my father, but he always spoke in this continental, literary accent, probably because he was a professor of comparative literature and he made the decision to speak with distinction.",
    "All of my characters have a glint of madness.",
    "Disney has a great tradition of enchanting children and giving them something to behold.",
    "I don't want to just do independent movies and I don't want to just do adventure films. I enjoy both, and I think both are cogent.",
    "I'm always curious about what happens when we die. And I'd like to think that somehow the spirit goes on. I'd rather not think that it's just about this.",
    "I have a love/ hate relationship with the city of New Orleans, which is the strongest kind of relationship.",
    "The biggest problem for me was feeling that as I became more balanced and a better man that I wouldn't have the fire to create from.",
    "Idris Elba is a grand actor. He's very larger than life; he's bigger than life.",
    "It's no secret that I've always had an interest in mythology. Whether it's Arthurian or ancient Greek or even Marvel universe. I've always connected with it on some level.",
    "I love England - it's no secret.",
    "Mel Blanc is a hero because of what he could do with his voice for all the Looney Tunes, the Warner Brothers cartoons, to be the voice of Bugs Bunny, Daffy Duck, Elmer Fudd, Porky Pig. To me, he's a great actor.",
    "I'll speak for myself, but there's a lot of humor to be found in sarcasm and darkness. You talk to any paramedic, they survive by developing a pretty off-kilter sense of humor.",
    "I don't want a perfect character, I want a character who has, as strange as it sounds, some humanity, some flaws, some needs.",
    "Guy Pearce is very precise and clear about understanding the rhythm and the music of a scene.",
    "I would like to hook up with one of the great Japanese filmmakers, like the master that made Ringu, and I would like to take 'The Wicker Man' to Japan, except this time he's a ghost.",
    "I haven't isolated myself. I am not living on a yacht somewhere. I am not tucked away or behind a gate somewhere. I am not flying on a private plane. I am going to the airport, I am with people, some of the interactions are good, some of them are not so good, but it keeps me in touch with being, you know, part of society.",
    "It's a family that's loaded with grudges and passion. We come from a long line of robbers and highwaymen in Italy, you know. Killers, even.",
    "I invite the entire spectrum, shall we call it, of feeling. Because that is my greatest resource as a film actor. I need to be able to feel everything, which is why I refuse to go on any kind of medication. Not that I need to! But my point is, I wouldn't even explore that, because it would get in the way of my instrument.",
    "I knew I wanted to be an actor when I was very young. I guess I was about 6 years old at the time, and I was fascinated by television. I started having waking fantasies where I was in a movie and there were crane shots of me during a scene.",
    "'Knowing' is one of those movies where you're going to get the spectacle, and you're going to have the entertainment in the grand science fiction tradition. But also, it will perhaps stimulate some discussion to help you sort out on your own where you might choose to go in terms of your own needs. Now, I say that without preaching.",
    "Children, to me, are of the utmost importance. They're really the future, aren't they?",
    "Good science fiction is intelligent. It asks big questions that are on people's minds. It's not impossible. It has some sort of root in the abstract.",
    "Mike Myers as Austin Powers makes me laugh - that was genius - and Daffy Duck makes me laugh, but I like odd behavior. I don't like hip dialogue and one-liners and all that sort of cool, sophomoric comedy. It's just not for me.",
    "The only reason why I tend to pass on a movie is either I don't think I'm right for the material and can't play it honestly, or because of time constraints with personal things in my life.",
    "When you start a movie, it's not like other kinds of work that you have when you know your boss for years or colleagues for years. You're meeting everyone, mostly, for the first time. You have to get comfortable with those people so you can perform, because the first thing that is going to shut you down is any kind of anxiety.",
    "When I'm in England, I know I'm a visitor, but being a white man in England with ancestry that's German and Italian, I have a history with the Romans and the Saxons. I feel some connection and ancestry here, as weird as that sounds.",
    "When I play supernatural characters in 'Ghost Rider' or 'City Of Angels,' the possibilities are limitless. The possibilities are endless, you can do so much with that.",
    "There were two movies that asked me to go to Australia or New Zealand for long periods of time. One was 'Lord of the Rings' and one was 'The Matrix.' But I was actively involved at that time raising my family, and I couldn't really take that time out.",
    "The best characters are the ones that somehow manage to be both attractive and repulsive at the same time. If you do that, you're at the center of the universe - if you can find characters who are more ambiguous and can raise more questions than answers.",
    "I don't want you to think that I'm up late reading a stack of Spider-Man comics and eating a tray of lemon cookies while sucking my thumb. I'm not doing that. But I am loyal to the influences of my childhood.",
    "My house is basically a trailer. I live a circus lifestyle. I'm always moving. It's not always easy for people that live with me, but that's the path I chose.",
    "One of the things that's interesting to me is I find things like caffeine and stunts actually relax me. When they're putting a bit of gel on my arm and lighting me on fire, or when I'm about to go into a high-speed car chase or rev a motorcycle up pretty fast, I find everything else around me slows down.",
    "It's kind of a unique concept, but it's totally real, isn't it? ... I mean, these paramedics put themselves in incredibly stressful situations, are killing themselves to save our lives and they're not really regarded or appreciated.",
    "I would love to work with Tim Burton. I think we would be very good together.",
    "I think that if you go about making movies to win Oscars, you\u2019re really going about it the wrong way.",
    "I think I've spent more time in front of a camera than off camera. That's just the way it is.",
    "I do enjoy animated movies.",
    "I may be alone in this, but I do sense the power of film, in that movies have the ability to literally change people's minds. That's pretty powerful stuff when you consider that.",
    "Actors work with their look. I come from the Lon Chaney Sr. school of acting. I'll wear wigs, I'll wear nose pieces, I'll wear green contact lenses in my eyes. I'll do whatever I need to do to create a character.",
    "My father always used to say to me, it doesn\u2019t matter what the profession is, but if they\u2019re the best in their field, it will always be fascinating to watch.",
    "I wasn't any good at romnace. I was a total nerd. My thing is, I was just too romantic. I was the romantic goofball. I wasn't cynical enough or harsh enough. I cared too much, so I always made a fool out of myself.",
    "I'm always fearful of something happening to people I love. That doesn't go away.",
    "That was one of the reasons why I wanted to tell the story of Colin Price. I saw someone in this fictionalized political character that was trying to do something important for his city. He meant well, but then you see that the human flaws had really derailed his past. It seems to be happening more and more in our country. I wanted to hold a mirror up to that.",
    "I do understand sometimes when actors say there's no one to talk to, or you can't react to, there's truth in that, but for me, I've always enjoyed green screen, and blue screen.",
    "I was thinking about being more global in my work, which means trying more foreign countries and working with foreign filmmakers, hoping they would give me a new take on my work, a new point of view, reinvent me in some way.",
    "I think that the best characters are the ones who both manage to be attractive and repulsive at the same time.",
    "When you have 400 people watching you making a movie, it doesn't go where you want it to go. It's a lot of pressure.",
    "Nobody can make a movie as exciting as Jerry Bruckheimer. When it's a Jerry Bruckheimer movie that it's going to have lots of chrome and gloss, it's going to be sexy, and it's going to be big and fun.",
    "I would say that I'm 98 percent skeptical, but the other 2 percent [is] open for the possibility of things.",
    "I certainly would never overstep my bounds and make suggestions to a director. As an actor I'm trying to fit to the best of my abilities within the director's vision, and trying to find some happy rapport where we can both bring something to it that's fresh. Usually I've been lucky in working with directors who have trusted my instincts.",
    "I've always believed that the greatest actors are the ones that have the voices that are imitable.",
    "I just want to keep making movies that hopefully makes some kids smile.",
    "Sometimes I do love to rehearse, but I always switch it up depending on whom I'm working with.",
    "You often feel like you are on a high wire with no net productions because you have to rely on spontaneity and come up with ideas on the spur of the moment - and then what happens is that there is electricity to it that gets caught.",
    "These so called Popcorn movies, or family movies, actually provide something quite beautiful and something quite necessary, which is a family bonding experience.",
    "God bless the popcorn film. Especially movies where you can take the kids, because I remember looking forward to seeing these movies with my parents, and if I can give that back, I'm gonna do it.",
    "I came out of independent film, that's my roots. I used my independent film as a laboratory, and used what I could discover in that laboratory.",
    "I try to keep my characters raising more questions than giving answers. I don't want to leave too much on the table. I want you to have your connection and your secret understanding of the character.",
    "When you're playing supernatural characters, there's an infinite number of possibilities with a character. And I also think they're wonderful and entertaining for the whole family. You don't have a high body count.",
    "I never say never, but I haven't been given the quality of script to compel me to go on television.",
    "Halloween has always been fascinating to me from a very young age. I think any actor would be fascinated by Halloween because it's one of the only holidays that advocates dressing up in makeup and costumes and transforming oneself.",
    "I love working with younger actors because they always come into the game full of energy and ideas that challenge me and keep me learning and stimulated.",
    'I actually enjoy working with green screen, because I can imagine all that stuff happening, and I really cut my teeth on a movie I made called "Adaptation" where I had to imagine four-page dialogue scenes with my twin brother, who was nothing more than a tennis ball and a gas stand.',
    "The most meaningful movies I can make are the ones where parents can share them with their children and children can look forward to sharing them with their parents, a ritual if you will, where they get to spend time together and the kids are smiling.",
    "I always wanted to find a way to apply my acting in a big mad monster movie where I was transforming into this scary entity.",
    "If you get a chance, whenever you're traveling, do go to the local boutique comic book shop and don't buy your comics online 'cause those guys are going to go extinct, in a minute here, and we want to be able to have those experiences with our kids.",
    "With every action oriented or adventure film, there's going to be a moment when every actor becomes a stuntman and every stuntman becomes an actor. You try to do as much of it as you can, but inevitably the studio wants you to finish the movie. So you've got to slow down and you're really got to defer to your team to make sure you do.",
    "I do like characters that have flaws, some sort of pathos to them that they are trying to sort out.",
    "I like the idea of being involved in pictures that can entertain the entire family and can stimulate youngsters into looking at picture books. There's nothing wrong with that.",
    "All movies on some level can aspire to be more than just whatever the label is of the movie.",
    "I got a little tired of movies where I had to shoot people. I got to thinking about the power of film and what that power is. The power is in fact that it really can change people's minds.",
    "Without impending on your own personal choice, there are going to be those that wear the hat of religion and those that wear the hat of science. I still don't really understand why they can't wear both hats, because personally, I think that they go beautifully together.",
    "Generally my instinct is to not do biographical movies. I want to build characters and not be locked into playing a part in history.",
    "In the beginning my energy and passion for acting came from an almost punk rock need to express a lot of anger wherever that may have come from. As I got older, it became or is coming more from a place of wanting to use the craft to help others in some way, to hold a mirror up to the situations that we're going through, to actually be more cautious about the way that I use the power of film and to see if there's anything that I can do in the performances that will resonate in the public a similar string that's on people's minds and is on my mind. That way we have that relationship.",
    "I want to try to apply my abilities sometimes to make families happy, so I have to make movies at a venue that are not gratuitously violent, that are not using bullets and bloodshed, but are using things like magic and fantasy and enchantment and the imagination. To me that's just all positive stuff. But I am eclectic and I still like to make movies for the midnight audience as well.",
    "I just try to keep it fresh. I try to keep it interesting. The truth is my roots are independently spirited dramas that are small, and I will always go back to that well, because that's where I broke out of. But I'm going to keep doing as many different movies as I possibly can.",
    "More than ever, movies reveal themselves as healing, as helpful, as encouraging, as escapist - anything that makes someone get through their day in these times. It's the best form of entertainment, and it's still arguably the most inexpensive form of entertainment.",
    "I really think it's important that my beliefs don't impinge upon what you get from the movie. It's your opinion that matters and it's far more interesting than mine.",
    "I was very happy with Vampire's Kiss, which in my opinion was almost like an independent laboratory to start realizing some of my more expressionistic dreams with film performance. Then using what I had learned in Vampire's Kiss and putting it into a very big action movie in the form of Face/Off with John Woo. If you look at those two movies back to back, you can see where I stole from my performance in Vampire's Kiss.",
    "I got into film acting because I wanted to be James Dean. We lost him at a very young age - he was only 24 - but I\u2019m 51 going on 52, so there's only so many times you can act like James Dean. I had to find new ways of expressing myself that kept me fascinated with film performance.",
    "I really would like to be able to face all my superstitions that may have existed and walk under the ladder and do everything you're not supposed to do.",
    "When I started experimenting with fantasy and horror films and looking for characters who had some sort of emotional or mental difficulty, I saw opportunities to express my music - dare I say art - in a way that I could get a bit surreal.",
    "I love art, I love music. I can listen to Stockhausen and a very experimental, avant-garde approach, and I can listen to Beethoven and have a more classical, traditional approach. Why not be able to do that with film performance?",
    "I went to New Orleans for the first time for Wild at Heart, and I kept going back to make more movies there. I've become very close to the city and part of me does feel like a New Orleanian.",
    "I find it inspiring and I always think when I'm working on something new, whether it's a new kind of character or a new kind of story or new kind of camera, it gets my creative wheels spinning.",
    "I had been making a lot of family oriented movies, which I also like. But I still have a passion for the midnight audience and for midnight movies.",
    "When you're playing a spirit from another dimension, you really can do anything and get as abstract as you want and still have a context that will work within the movie. I wanted Ghost Rider to move in a way where it would be like a bad dream. I thought about cobra snakes, and the way that they will show you their backs and sway in a rhythmic motion and almost lull you to sleep before suddenly attacking. Well, I put that into the movie. And I decided to move my head in the jerky way a praying mantis does. So, I did all these things to give the movie a feeling of otherness.",
    "People often say that you should never work with child actors. I think that's all wrong. Children have not had the imagination kicked out of them by life experience and adulthood. So, they still are very much alive with that kind of magical thinking which enables an actor to believe they're in these circumstances and make them real to you.",
    "I don't find the same things funny that many other people seem to find funny. I don't really respond to sex jokes and things like that, and some of my friends look at me and go, \"Come on, Nic, that was my best joke. Why aren't you laughing?\" I go, \"I really don't know why I'm not laughing. I'm sort of out of sync with it.\" So I'd have to find something that was really about weird human behavior for me to laugh.",
    "I don't know why it is, but I do like dancing in the extreme situations. I like that noise, I like that intensity. For some reason, it's what I respond to in terms of my taste and of my instincts.",
    "I find children inspiring. The way they look at the world. The magical world they live in, to me, is inspiring.",
    "Movies work, in my opinion, on the best level when they're more enigmatic, when we don't say it's this or that and where it raises more questions than answers.",
    "I think a good movie is a good movie whether that falls into a genre or not.",
    "When I work, I really try to get absorbed in the character. Unless I want to do something playful with the camera, I'm not too worried about where the camera is or positions.",
]

def get():
    i = random.randint(0, 1)
    if i == 1:
        return get_nicgif()
    else:
        return random.choice(nicQuotes)